FROM alpine:3.23
RUN apk add --no-cache python3 py3-aiohttp openssl
ARG UID=1000
ARG GID=1000
RUN addgroup -S -g "$GID" rdircd && adduser -S -h /config -s /bin/false -G rdircd -DH -u "$UID" rdircd
COPY rdircd/rdircd rdircd/rdircd.unicode-emojis.txt.gz /
USER rdircd:rdircd
ENV PYTHONUNBUFFERED=1
EXPOSE 6667
VOLUME /config
WORKDIR /config
ENTRYPOINT ["/rdircd", "--conf", "config.ini", "-i", "0.0.0.0"]
